### ISSUE TITLE
JavaScript capstone project setup

### ISSUE THREAD

**Issue by tariktesfa** [HAMMAS-SALEEM/INFLIX#21]
These [is our repository](https://github.com/HAMMAS-SALEEM/Foodeez/) and [our project link](https://github.com/HAMMAS-SALEEM/Foodeez/projects/1).
We are a group of two. 

- Hammas Bin Saleem- Student A
- Tarikwa Teasfa- Student B

**Comment by Meltrust** [comment]
Hi @tariktesfa, 

Your project is complete!   :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HAMMAS-SALEEM** [comment]
Thanks for giving us a thorough review of our first GitHub Project. Now we can submit this repo by closing this issue. 👍 
Thanks again for reaching out to us🚀
